server:
  port: 8080



#mybatis:
#  type-aliases-package: com.maigechuang.entity
 # mapper-locations: classpath*:mapper/**.xml
  #configuration:
   # use-generated-keys: true
    #map-underscore-to-camel-case: true
